name: Lint

on:
  push:
    branches:
      - production
      - beta
      - canary
    paths-ignore:
      - '**.md'
      - '.github/**'
      - '!.github/workflows/lint.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ^1.22
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v5
        with:
          version: latest
          args: --timeout=30m
          install-mode: binary